from django.conf.urls import patterns, url
from maximatch import views

urlpatterns = patterns('',
                       url(r'^$',
                           views.index,
                           name='index'),
                       url(r'^add_experiment/$',
                           views.add_experiment,
                           name='add_experiment'),
                       url(r'^apply_experiment/(?P<experiment_title_url>\w+)/$',
                           views.apply_experiment,
                           name='apply_experiment'),
                       url(r'^view_participants/(?P<experiment_title_url>\w+)/$',
                           views.view_participants,
                           name='view_participants'),
                       url(r'^update_application_status/$',
                           views.update_application_status,
                           name='update_application_status'),
                       url(r'^experiment/(?P<experiment_title_url>\w+)/$',
                           views.experiment,
                           name='experiment'),
                       url(r'^edit_experiment/(?P<experiment_title_url>\w+)/$',
                           views.edit_experiment,
                           name='edit_experiment'),
                       url(r'^previous_experiments/$',
                           views.previous_experiments,
                           name='previous_experiments'),
                       url(r'^settings/$', views.settings, name='register'),
                       url(r'^restricted/$', views.restricted, name='restricted'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^register_participant/$', views.register_participant, name='register_participant'),
                       url(r'^register_researcher/$', views.register_researcher, name='register_researcher'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^user_details/(?P<username>\w+)/$',
                           views.user_details,
                           name='user_details'),
                )
